{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "c723dcdc_840b590f",
        "filename": "lib/sensor_info_record.py",
        "patchSetId": 13
      },
      "lineNbr": 8,
      "author": {
        "id": 1000027
      },
      "writtenOn": "2022-09-22T17:50:39Z",
      "side": 1,
      "message": "I observe that there is no try and catch block for exception handling.. how to handle in case of failures?",
      "revId": "1d1e494cf08adbda9e665d67d708c25325845094",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}